artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source: https://drive.google.com/uc?id=1mFOfDcOlMbPRuSlDJOk1iQfYJtkPZliQ
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/helmet_data/

data_validation:
  root_dir: artifacts/data_validation
  data_validation_status_file: artifacts/data_validation/status.txt
  data_validation_required_file: ["train","valid","test","data.yaml"]
